"""PlatformIO pre-script: gzip the big /settings page body at build time.

The /settings page body is ~56 KB raw HTML/CSS/JS. The ESP32-S3 has
miniz in ROM but the tdefl_compressor struct is ~280 KB - too big
for our heap. So we precompress at build time and serve the
precompressed bytes via a /settings/body.gz endpoint with
Content-Encoding: gzip.

Reads `src/wb_web.cpp` between PRECOMPRESS_SETTINGS_BODY_BEGIN/END
markers, gzips the R"HTML(...)HTML" content, and writes a PROGMEM
byte array to `include/_gen_settings_body_gz.h`.
"""

from __future__ import annotations
import gzip
import hashlib
import re
from pathlib import Path

Import("env")  # type: ignore

SOURCE = Path("src/wb_web.cpp")
HEADER = Path("include/_gen_settings_body_gz.h")
MARKER_BEGIN = "// PRECOMPRESS_SETTINGS_BODY_BEGIN"
MARKER_END = "// PRECOMPRESS_SETTINGS_BODY_END"


def _extract_body(src):
    if MARKER_BEGIN not in src or MARKER_END not in src:
        raise SystemExit(
            "[precompress_settings] markers not found in src/wb_web.cpp"
        )
    block = src.split(MARKER_BEGIN, 1)[1].split(MARKER_END, 1)[0]
    m = re.search(r'R"HTML\(\n?(.*?)\n?\)HTML"', block, re.DOTALL)
    if not m:
        raise SystemExit(
            "[precompress_settings] no R\"HTML literal inside markers"
        )
    return m.group(1)


def _format_bytes(blob):
    out = []
    for i in range(0, len(blob), 16):
        chunk = blob[i:i + 16]
        out.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    return "\n".join(out)


def main():
    src = SOURCE.read_text(encoding="utf-8")
    raw = _extract_body(src).encode("utf-8")
    gz = gzip.compress(raw, compresslevel=9, mtime=0)
    sha = hashlib.sha256(raw).hexdigest()
    HEADER.parent.mkdir(parents=True, exist_ok=True)
    body = (
        "// AUTO-GENERATED by scripts/precompress_settings.py - DO NOT EDIT.\n"
        f"// Source: src/wb_web.cpp, sha256[:16]={sha[:16]}\n"
        "#pragma once\n#include <pgmspace.h>\n"
        "#include <stddef.h>\n#include <stdint.h>\n\n"
        f"const size_t SETTINGS_BODY_GZ_LEN  = {len(gz)};\n"
        f"const size_t SETTINGS_BODY_RAW_LEN = {len(raw)};\n\n"
        "const uint8_t SETTINGS_BODY_GZ[] PROGMEM = {\n"
        f"{_format_bytes(gz)}\n}};\n"
    )
    existing = HEADER.read_text(encoding="utf-8") if HEADER.exists() else ""
    action = "wrote" if existing != body else "unchanged"
    if action == "wrote":
        HEADER.write_text(body, encoding="utf-8")
    ratio = (1.0 - len(gz) / len(raw)) * 100.0
    print(
        f"[precompress_settings] raw={len(raw)} gz={len(gz)} "
        f"({ratio:.1f}% reduction) -> {HEADER} ({action})"
    )


main()
