"""PlatformIO pre-script: gzip big page bodies at build time.

Large page bodies (~30-56 KB raw HTML/CSS/JS) can't be gzipped on-device
(miniz's tdefl_compressor is ~280 KB, too big for our heap), and building
them as a runtime String is a heap-fragmentation risk. So we precompress
each at build time and serve the bytes via a /<page>/body.gz endpoint with
Content-Encoding: gzip — the server never allocates the big String.

For each page below, reads `src/wb_web.cpp` between its BEGIN/END markers,
gzips the R"HTML(...)HTML" content, and writes a PROGMEM byte array to the
matching `include/_gen_<page>_body_gz.h`.

To precompress a new page: wrap its static body in an `#if 0` block with
`// PRECOMPRESS_<PAGE>_BODY_BEGIN` / `_END` markers around an R"HTML(...)"
literal, add an entry to PAGES, and serve <PREFIX>_BODY_GZ.
"""

from __future__ import annotations
import gzip
import hashlib
import re
from pathlib import Path

Import("env")  # type: ignore

SOURCE = Path("src/wb_web.cpp")

# (marker prefix, output header, C++ var prefix)
PAGES = [
    ("PRECOMPRESS_SETTINGS_BODY",  "include/_gen_settings_body_gz.h",  "SETTINGS"),
    ("PRECOMPRESS_INFO_BODY",      "include/_gen_info_body_gz.h",      "INFO"),
    ("PRECOMPRESS_DASHBOARD_BODY", "include/_gen_dashboard_body_gz.h", "DASH"),
]


def _extract_body(src, marker):
    begin = f"// {marker}_BEGIN"
    end = f"// {marker}_END"
    if begin not in src or end not in src:
        raise SystemExit(f"[precompress] markers for {marker} not found in {SOURCE}")
    block = src.split(begin, 1)[1].split(end, 1)[0]
    m = re.search(r'R"HTML\(\n?(.*?)\n?\)HTML"', block, re.DOTALL)
    if not m:
        raise SystemExit(f"[precompress] no R\"HTML literal inside {marker} markers")
    return m.group(1)


def _format_bytes(blob):
    out = []
    for i in range(0, len(blob), 16):
        chunk = blob[i:i + 16]
        out.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    return "\n".join(out)


def _gen_page(src, marker, header_path, prefix):
    header = Path(header_path)
    raw = _extract_body(src, marker).encode("utf-8")
    gz = gzip.compress(raw, compresslevel=9, mtime=0)
    sha = hashlib.sha256(raw).hexdigest()
    header.parent.mkdir(parents=True, exist_ok=True)
    body = (
        "// AUTO-GENERATED by scripts/precompress_settings.py - DO NOT EDIT.\n"
        f"// Source: src/wb_web.cpp ({marker}), sha256[:16]={sha[:16]}\n"
        "#pragma once\n#include <pgmspace.h>\n"
        "#include <stddef.h>\n#include <stdint.h>\n\n"
        f"const size_t {prefix}_BODY_GZ_LEN  = {len(gz)};\n"
        f"const size_t {prefix}_BODY_RAW_LEN = {len(raw)};\n\n"
        f"const uint8_t {prefix}_BODY_GZ[] PROGMEM = {{\n"
        f"{_format_bytes(gz)}\n}};\n"
    )
    existing = header.read_text(encoding="utf-8") if header.exists() else ""
    action = "wrote" if existing != body else "unchanged"
    if action == "wrote":
        header.write_text(body, encoding="utf-8")
    ratio = (1.0 - len(gz) / len(raw)) * 100.0
    print(f"[precompress] {prefix}: raw={len(raw)} gz={len(gz)} "
          f"({ratio:.1f}% reduction) -> {header} ({action})")


def main():
    src = SOURCE.read_text(encoding="utf-8")
    for marker, header_path, prefix in PAGES:
        _gen_page(src, marker, header_path, prefix)


main()
